### ISSUE TITLE
Pin sorted-nearest to 0.0.33

### ISSUE THREAD

**Issue by haimasree** [kipoi/kipoiseq#109]
sorted-nearest released a new version on May 27th. All nightly tests across kipoi repos(kipoi, models, website, kipoi-containers, kipoi-veff2) with kipoiseq as a dependency have been failing since then. The main error is as follows - 
```
Traceback (most recent call last):
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoi_utils/utils.py", line 134, in load_obj
    module = importlib.import_module(module_name)
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoiseq/__init__.py", line 11, in <module>
    from . import dataloaders
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoiseq/dataloaders/__init__.py", line 1, in <module>
    from .sequence import *
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoiseq/dataloaders/sequence.py", line 3, in <module>
    import pyranges as pr
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/pyranges/__init__.py", line 137, in <module>
    import pyranges.genomicfeatures as gf
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/pyranges/genomicfeatures.py", line 7, in <module>
    from sorted_nearest.src.introns import find_introns
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/sorted_nearest/__init__.py", line 7, in <module>
    from sorted_nearest.src.k_nearest_ties import get_all_ties, get_different_ties
ImportError: cannot import name 'get_all_ties' from 'sorted_nearest.src.k_nearest_ties' (/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/sorted_nearest/src/k_nearest_ties.cpython-37m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoi_utils/utils.py", line 140, in load_obj
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/circleci/repo/epidermal_basset/encode-roadmap.basset.clf.testfold-0/kipoiseq.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoi/__main__.py", line 107, in main
    command_fn(args.command, sys.argv[2:])
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoi/cli/main.py", line 69, in cli_test
    mh = kipoi.get_model(args.model, args.source)
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoi/model.py", line 125, in get_model
    default_dataloader = md.default_dataloader.get()
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoi/specs.py", line 805, in get
    obj = load_obj(self.defined_as)
  File "/home/circleci/miniconda3/envs/test-kipoi-epidermal_basset__encode-roadmap.basset.clf.testfold-0/lib/python3.7/site-packages/kipoi_utils/utils.py", line 143, in load_obj
    raise ImportError("object {} couldn't be imported. Error {}".format(obj_import, str(e)))
ImportError: object kipoiseq.dataloaders.SeqIntervalDl couldn't be imported. Error [Errno 2] No such file or directory: '/home/circleci/repo/epidermal_basset/encode-roadmap.basset.clf.testfold-0/kipoiseq.py'

```
kipoiseq depends on pyranges which depends on sorted-nearest. This issue has been reported [here](https://github.com/pyranges/sorted_nearest/issues/5). Unless this is fixed at source only way to keep kipoiseq usable will be to pin sorted-nearest in kipoiseq.

**Comment by haimasree** [comment]
As mentioned [here](https://github.com/pyranges/sorted_nearest/issues/5) this is no longer necessary. Closing the issue :)
